version: "3.8"
services:
  shopecom-service:
    image: assaduzzaman/shopecom-ui
    container_name: shopecom-ui
    depends_on:
      - keycloak
      - shopecom-api
    ports:
      - 80:80
  shopecom-api:
    image: assaduzzaman/shopecom-api
    container_name: shopecom-api
    depends_on:
      - keycloak
      - mysqldb
    expose:
      - 8000  
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.3
    container_name: keycloak
    command: start-dev --import-realm
    # command: start-dev
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./data/db-dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=full-stack-ecommerce  
    ports:
      - 3306:3306


