version: "3.8"
services:
  shopecom-service:
    image: assaduzzaman/shopecom-ui
    container_name: shopecom-ui
    depends_on:
      - keycloak
      - shopecom-api
    ports:
      - 80:80
  shopecom-api:
    image: assaduzzaman/shopecom-api
    container_name: shopecom-api
    depends_on:
      - keycloak
      - mysqldb
    expose:
      - 8000  
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    # command: start-dev --import 
    command: start-dev
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    expose:
      - 8080

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306


