version: "3.8"
services:
  # Applications
  shopecom-service:
    # Build image with "./gradlew bootBuildImage from edge-service project"
    image: shopecom-service
    container_name: shopecom-service
    depends_on:
      - keycloak
    ports:
      - 80:80
  
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.3
    container_name: keycloak
    # command: start-dev --import-realm
    command: start-dev
    # volumes:
    #   - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
